set number         " Show line numbers
set tabstop=4      " Number of spaces a tab in the text stands for
set softtabstop=4  " Number of spaces in an automatic indent
set expandtab      " Use spaces instead of tabs
syntax on          " Enable syntax highlighting

